### ISSUE TITLE
Problem with compilinf for the first time

### ISSUE THREAD

**Issue by gniewus** [reTHINK-project/dev-msg-node-vertx#16]
Hello,

I'm a freshman in  the project and I'm trying to compile dev-msg-node-vertex. I'm working on Ubunutu  and every time after running 'sudo  npm run init-setup' i get this:

Error: Cannot find module '/home/tomasz/dev-msg-node-vertx/setup.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

Do you have any ideas how to solve my issue ?
Thank you for your help
Tomasz

**Comment by shumy** [comment]
Yes sorry, that is a old config. I just updated/cleaned the package.json file. You just need to run "npm install".
JavaScript in this repository is just needed for the Protostub build and karma tests.
