### ISSUE TITLE
Persistence of MN Subscriptions

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-msg-node-vertx#29]
The Subscription Manager should persist listeners added to BUS in order not to loose them in case it is for some reason rebooted. When rebooted, the Subscription Manager should look on persisted subscriptions and add them again as listeners into the BUS.

**Comment by luistduarte** [comment]
Vertx in-memory data grid based on Hazelcast is used to persiste data.

This means Vertx has to be deployed in Cluster Mode. When one of them for some reason goes down, when it is rebooted it will get back every subscriptions registered.
