### ISSUE TITLE
7 branches on vertx node. Which one is good/stable?

### ISSUE THREAD

**Issue by sbecot** [reTHINK-project/dev-msg-node-vertx#30]
I installed the develop one because the master seems to have connector issue. By the way, I still have a communication problem with the registry.

**Comment by pchainho** [comment]
yes, develop should be ok. We should merge and have a new release very soon

**Comment by pchainho** [comment]
@rjflp could someone from your side give some support to @sbecot ?

**Comment by rjflp** [comment]
We know there is currently a discrepancy between the versions of the runtime and the connector, due to a new release of the runtime. We already have a branch that accepts the new version of the message. We will release soon.

@sbecot can you please point to the issue, so we can make sure it is the same problem?

**Comment by sbecot** [comment]
It is on the dev-msg-node slack channel. But it seems that the registry is not even called. Not sure where the pb comes from.

**Comment by sbecot** [comment]
Well, I progressed. I installed the nomatrix mn. It was working better but still not communicating with the registry but the traces are more explicit. I finally found that the apache reverse proxy has a problem with encoded urls. 
For example https://registry.csp.rethink3.orange-labs.fr:4567/hyperty/user/user%3A%2F%2Fgmail.com%2Fjohnny.macmuller/hyperty%3A%2F%2Fcsp.rethink3.orange-labs.fr%2F641ac3 dc-c578-443c-913e-9bde38826d61
is not treated like https://registry.csp.rethink3.orange-labs.fr:4567/hyperty/user/user://gmail.com/johnny.macmuller/hyperty://csp.rethink3.orange-labs.fr/641ac3 dc-c578-443c-913e-9bde38826d61
The virtual host necessitates a specific directive:
`AllowEncodedSlashes On`

To be honnest, the service is working as before, but at least the registry is registering the hyperties. 
Finally I came back to the Vertx and the problem is still the same. In fact the registry don't even get a request from the node:
[REGISTRY-CONNECTOR] Error: io.vertx.core.VertxException: Connection was closed
[REGISTRY-CONNECTOR] Error: io.vertx.core.VertxException: Connection was closed
[REGISTRY-CONNECTOR] Error: io.vertx.core.VertxException: Connection was closed
[REGISTRY-CONNECTOR] Error: io.vertx.core.VertxException: Connection was closed
[REGISTRY-CONNECTOR] Error: io.vertx.core.VertxException: Connection was closed

**Comment by sbecot** [comment]
Anyway, 7 branches is a lot, and some of then don't have a significant name. As proposed here https://github.com/reTHINK-project/core-framework/blob/master/docs/methodology/readme.md#version-control

**Comment by luistduarte** [comment]
Insignificant branchs already deleted

**Comment by rjflp** [comment]
Regarding the domain registry, the issue seemed to be with the reverse proxy configuration on the Orange test bed. I'm closing this issue. Please open if needed.
