### ISSUE TITLE
Registry Connector 0.8.0 and 0.8.1 version

### ISSUE THREAD

**Issue by luistduarte** [reTHINK-project/dev-msg-node-vertx#39]
After this merge we got this error using docker-hub image. 
![screenshot from 2017-03-21 12 01 27](https://cloud.githubusercontent.com/assets/11315256/24146592/3f1f59e6-0e2e-11e7-8317-b6c3f5324607.png)
You should check if nashorn is compatible with your code...

**Comment by nunofmn** [comment]
Here is working fine, and I tested it before submitting the pull request.
When deploying in docker is the `MSG_NODE_CONFIG` environment variable defined to `prod`?
I didn't define the newest fields in the `prod` settings in `node.config.json` since I was not sure if TLS/SSL support was wanted by default

**Comment by luistduarte** [comment]
When we use MSG_NODE_CONFIG=env, there is not environment variables available on documentation available for configure registry.ssl.enable and registry.retries, So I added both and I made some changes to deal with it. I added both env variables on [README.md](https://github.com/reTHINK-project/dev-msg-node-vertx/blob/develop/README.md#3-config-vertxmn-domain)

**Comment by pchainho** [comment]
@nunofmn pls update your docs when required and warn your "clients" about these changes

**Comment by nunofmn** [comment]
@pchainho I updated the connector docs, in [Domain Registry repository](https://github.com/reTHINK-project/dev-registry-domain/blob/master/docs/RegistryConnectorManual.md) and added a section in the this repository README [here](https://github.com/reTHINK-project/dev-msg-node-vertx/tree/develop#registry-connector-configuration).

@luistduarte to enable SSL/TLS is necessary to create a set of certificates. In [Registry Connector configuration section] in this repository README there link for the instructions of how to configure.

**Comment by luistduarte** [comment]
Can this set of certificates be available somewhere to download and usage?

**Comment by nunofmn** [comment]
If the msg-node is able to communicate with the Domain Registry, and the DR is deployed with SSL/TLS enabled (with or without load balancer), it should be ok.

**Comment by luistduarte** [comment]
@nunofmn i got a question for you, registry-domain server will use this certificates, or is just for registry-domain connector of vertx?

**Comment by nunofmn** [comment]
The Domain Registry also need a certificate. If you also deploy the load balancer you will need also another certificate. More details in [Domain Registry Manual](https://github.com/reTHINK-project/dev-registry-domain/blob/master/docs/DomainRegistryUserManual.md)
