### ISSUE TITLE
Vertx MN does not support address de-allocation by childrenResources

### ISSUE THREAD

**Issue by sdruesedow** [reTHINK-project/dev-msg-node-vertx#51]
The Vertx MN does not implement de-allocation of addresses via "body.childrenResources". ( see [spec.](https://github.com/reTHINK-project/specs/blob/master/messages/address-allocation-messages.md#address-deallocation-request-for-one-or-more-addresses) ) 
It only supports de-allocation via an allocation-key in "body.resource".

It shall be ensured that the spec is not obsolete, since obviously this feature seems not widely used in the current implementations.

**Comment by pchainho** [comment]
Luis, pls have a look on this

**Comment by sdruesedow** [comment]
This issue is relevant for D6.4. If not solved then the conformance tests will report missing features for the VertX node.

**Comment by pchainho** [comment]
I think it has been implemented: @luistduarte can you confirm?

**Comment by luistduarte** [comment]
it is implemented on develop branch

**Comment by sdruesedow** [comment]
tested successfully against develop branch --> closing
