### ISSUE TITLE
Vertx MN domain registration issues

### ISSUE THREAD

**Issue by sdruesedow** [reTHINK-project/dev-msg-node-vertx#53]
The Vertx MN contradicts with the spec for domain registration messages in two points:

1. The "from" field of messages sent to the MN for the domain registry is specified to start with "hyperty-runtime://" (see [registration-messages.md](https://github.com/reTHINK-project/specs/blob/master/messages/registration-messages.md#registration-request) )
The Vertx MN instead only works for "from" fields starting with "runtime://" and throws a NullPointerException otherwise.
```
msg-node-vertx-local | 2017-06-07 10:17:53 INFO  BROKER - IN: (id: 1, type: open, from: hyperty-runtime://localhost/1, to: mn:/session)
msg-node-vertx-local | 2017-06-07 10:17:53 INFO  BROKER - RESOLVED: hyperty-runtime://localhost/1 - TO null
msg-node-vertx-local | T-HYPERTY: hyperty-runtime://localhost/1
msg-node-vertx-local | java.lang.NullPointerException
msg-node-vertx-local |  at eu.rethink.mn.pipeline.handlers.TransitionPipeHandler.handle(TransitionPipeHandler.java:45)
msg-node-vertx-local |  at eu.rethink.mn.pipeline.handlers.TransitionPipeHandler.handle(TransitionPipeHandler.java:33)
msg-node-vertx-local |  at eu.rethink.mn.pipeline.PipeContext.next(PipeContext.java:172)
msg-node-vertx-local |  at eu.rethink.mn.pipeline.handlers.ValidatorPipeHandler.handle(ValidatorPipeHandler.java:63)
msg-node-vertx-local |  at eu.rethink.mn.pipeline.handlers.ValidatorPipeHandler.handle(ValidatorPipeHandler.java:35)
msg-node-vertx-local |  at eu.rethink.mn.pipeline.PipeContext.next(PipeContext.java:172)
msg-node-vertx-local |  at eu.rethink.mn.pipeline.Pipeline.process(Pipeline.java:45)
...
```

2. The Vertx MN only works if the "to" field of registration messages ends with a "/", e.g.:
```
domain://registry.localhost/
```
instead of 
```
domain://registry.localhost
```
otherwise it does not return responses and the testcases fail.

**Comment by pchainho** [comment]
@luistduarte can you have a look on this pls?

**Comment by sdruesedow** [comment]
any updates?

**Comment by sdruesedow** [comment]
I'm documenting the situation for D6.4 as it is

**Comment by emmelmann-fokus** [comment]
Hi,

From WP-6 perspective, I am fine with this as we have to only assess the work in WP-6 and provide feedback to the technical WPs.

But from an overall perspective, this will raise issues in the final review, i.e., 
  * that a technical issue, that features having had worked before, were not working any more,
  * that this situation had been reported to the technical WPs, and
  * that a solution was not found within a month, nor was there a documented follow-up discussion.

Just my two cents.

**Comment by luistduarte** [comment]
Sorry for the delay. I did a fix on vertx branch develop, now it works with ```domain://registry.localhost```

**Comment by sdruesedow** [comment]
I tested the latest develop version. The issue with the trailing "/" is solved, the other one remains. There are still NullPointerExceptions if the "from" field starts with "hyperty-runtime://".

**Comment by luistduarte** [comment]
it is fixed now.

**Comment by sdruesedow** [comment]
confirmed for develop branch --> closing
